/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface PwActivityJobs {
  activity_name: string;
  attempt: number;
  completed_at: Timestamp | null;
  created_at: Timestamp;
  error: string | null;
  idempotency_key: string | null;
  input: Json | null;
  job_id: string;
  lease_expires_at: Timestamp | null;
  lease_token: string | null;
  max_attempts: number;
  result: Json | null;
  status: string;
  visible_at: Timestamp;
  workflow_run_id: string | null;
}

export interface PwWorkflowFailureHooks {
  activity_job_id: string | null;
  activity_name: string;
  completed_at: Timestamp | null;
  created_at: Timestamp;
  error: string | null;
  hook_seq: number;
  input: Json | null;
  result: Json | null;
  status: string;
  updated_at: Timestamp;
  workflow_run_id: string;
}

export interface PwWorkflowRuns {
  attempt: number;
  completed_at: Timestamp | null;
  created_at: Timestamp;
  error: string | null;
  idempotency_key: string | null;
  input: Json | null;
  lease_expires_at: Timestamp | null;
  lease_token: string | null;
  max_attempts: number;
  result: Json | null;
  status: string;
  updated_at: Timestamp;
  visible_at: Timestamp;
  workflow_name: string;
  workflow_run_id: string;
  workflow_worker_id: string | null;
}

export interface PwWorkflowSignals {
  consumed_at: Timestamp | null;
  consumed_by_wait_seq: number | null;
  created_at: Timestamp;
  idempotency_key: string | null;
  payload: Json;
  signal_id: string;
  signal_name: string;
  signal_seq: Generated<Int8>;
  workflow_run_id: string;
}

export interface PwWorkflowSignalWaits {
  completed_at: Timestamp | null;
  created_at: Timestamp;
  signal_name: string;
  wait_seq: number;
  workflow_run_id: string;
}

export interface PwWorkflowSteps {
  activity_job_id: string;
  activity_name: string;
  completed_at: Timestamp | null;
  created_at: Timestamp;
  error: string | null;
  input: Json | null;
  result: Json | null;
  status: string;
  step_seq: number;
  updated_at: Timestamp;
  workflow_run_id: string;
}

export interface PwWorkflowTimers {
  created_at: Timestamp;
  fire_at: Timestamp;
  timer_seq: number;
  workflow_run_id: string;
}

export interface DB {
  pw_activity_jobs: PwActivityJobs;
  pw_workflow_failure_hooks: PwWorkflowFailureHooks;
  pw_workflow_runs: PwWorkflowRuns;
  pw_workflow_signal_waits: PwWorkflowSignalWaits;
  pw_workflow_signals: PwWorkflowSignals;
  pw_workflow_steps: PwWorkflowSteps;
  pw_workflow_timers: PwWorkflowTimers;
}
